# Generated by Django 3.2.18 on 2023-04-04 22:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de registro')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('receipt_number', models.CharField(max_length=25, verbose_name='N° de recibo')),
                ('amount', models.FloatField(verbose_name='Total a pagar')),
            ],
            options={
                'verbose_name': 'Otro ingreso',
                'verbose_name_plural': 'Otros ingresos',
            },
        ),
        migrations.CreateModel(
            name='ServiceProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('project.service',),
        ),
        migrations.CreateModel(
            name='PaymentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de registro')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('receipt_number', models.CharField(max_length=25, verbose_name='N° de recibo')),
                ('amount', models.FloatField(verbose_name='Total a pagar')),
                ('payment_type', models.CharField(choices=[('0', 'Cuota por paja'), ('1', 'Cobro por activación')], default='0', max_length=2, verbose_name='Tipo de cobro')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='project.service', verbose_name='Paja de agua')),
            ],
            options={
                'verbose_name': 'Cobro',
                'verbose_name_plural': 'Cobros',
            },
        ),
        migrations.CreateModel(
            name='MonthlyFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('payment_date', models.DateField(verbose_name='Fecha de lectura')),
                ('previous_meters', models.FloatField(help_text='Corresponde a la lectura del mes anterior', verbose_name='Lectura anterior')),
                ('current_meters', models.FloatField(verbose_name='Lectura actual')),
                ('receipt_number', models.CharField(max_length=25, verbose_name='N° de recibo')),
                ('state', models.BooleanField(default=False, verbose_name='Pagado')),
                ('meters', models.FloatField(verbose_name='Metros consumidos')),
                ('amount', models.FloatField(verbose_name='Total a pagar')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_fee', to='project.service', verbose_name='Paja de agua')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
            },
        ),
    ]
