# Generated by Django 3.2.18 on 2023-04-04 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de registro')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('receipt_number', models.CharField(max_length=25, verbose_name='N° de recibo')),
                ('amount', models.FloatField(verbose_name='Total a pagar')),
                ('receiver_name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('receiver_dui', models.CharField(max_length=20, verbose_name='DUI')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
