# Generated by Django 3.2.18 on 2023-04-04 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('dui', models.CharField(max_length=20, verbose_name='DUI')),
                ('phone', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('photo', models.ImageField(blank=True, upload_to='members/photo', verbose_name='Foto')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Lugar')),
                ('department', models.CharField(max_length=70, verbose_name='Departamento')),
                ('municipality', models.CharField(max_length=70, verbose_name='Municipio')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='project.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Nombre')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('acquisition_date', models.DateField(verbose_name='Fecha de Adquisición')),
                ('price', models.FloatField(verbose_name='Precio de adquisición')),
                ('state', models.BooleanField(default=True, verbose_name='Activa')),
                ('paid', models.BooleanField(default=False, verbose_name='Pagada')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='project.member', verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Paja',
                'verbose_name_plural': 'Pajas',
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('min_meters', models.FloatField(default=0, verbose_name='Metros mínimos')),
                ('max_meters', models.FloatField(default=0, verbose_name='Metros máximos')),
                ('price', models.FloatField(default=0, verbose_name='Precio')),
                ('option_price', models.CharField(choices=[('0', 'metro'), ('1', 'cuota fija')], default='1', max_length=2, verbose_name='Precio por')),
                ('state', models.BooleanField(default=False, verbose_name='Estado')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='project.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='project.zone', verbose_name='Zona'),
        ),
    ]
